//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_club_H
#define METASPRITE_club_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define club_TILE_ORIGIN 0
#define club_TILE_H 8
#define club_WIDTH 16
#define club_HEIGHT 16
#define club_TILE_COUNT 4
#define club_PIVOT_X 0
#define club_PIVOT_Y 0
#define club_PIVOT_W 16
#define club_PIVOT_H 16

BANKREF_EXTERN(club)

extern const palette_color_t club_palettes[2];
extern const uint8_t club_tiles[64];

extern const metasprite_t* const club_metasprites[1];

#endif