//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_diamond_H
#define METASPRITE_diamond_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define diamond_TILE_ORIGIN 0
#define diamond_TILE_H 8
#define diamond_WIDTH 16
#define diamond_HEIGHT 16
#define diamond_TILE_COUNT 4
#define diamond_PIVOT_X 0
#define diamond_PIVOT_Y 0
#define diamond_PIVOT_W 16
#define diamond_PIVOT_H 16

BANKREF_EXTERN(diamond)

extern const palette_color_t diamond_palettes[2];
extern const uint8_t diamond_tiles[64];

extern const metasprite_t* const diamond_metasprites[1];

#endif