//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_heart_H
#define METASPRITE_heart_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heart_TILE_ORIGIN 0
#define heart_TILE_H 8
#define heart_WIDTH 16
#define heart_HEIGHT 16
#define heart_TILE_COUNT 4
#define heart_PIVOT_X 0
#define heart_PIVOT_Y 0
#define heart_PIVOT_W 16
#define heart_PIVOT_H 16

BANKREF_EXTERN(heart)

extern const palette_color_t heart_palettes[2];
extern const uint8_t heart_tiles[64];

extern const metasprite_t* const heart_metasprites[1];

#endif