//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_spade_H
#define METASPRITE_spade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spade_TILE_ORIGIN 0
#define spade_TILE_H 8
#define spade_WIDTH 16
#define spade_HEIGHT 16
#define spade_TILE_COUNT 4
#define spade_PIVOT_X 0
#define spade_PIVOT_Y 0
#define spade_PIVOT_W 16
#define spade_PIVOT_H 16

BANKREF_EXTERN(spade)

extern const palette_color_t spade_palettes[2];
extern const uint8_t spade_tiles[64];

extern const metasprite_t* const spade_metasprites[1];

#endif