//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_symbol_diamond_H
#define METASPRITE_symbol_diamond_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define symbol_diamond_TILE_ORIGIN 0
#define symbol_diamond_TILE_H 8
#define symbol_diamond_WIDTH 16
#define symbol_diamond_HEIGHT 16
#define symbol_diamond_TILE_COUNT 4
#define symbol_diamond_PIVOT_X 0
#define symbol_diamond_PIVOT_Y 0
#define symbol_diamond_PIVOT_W 16
#define symbol_diamond_PIVOT_H 16

BANKREF_EXTERN(symbol_diamond)

extern const palette_color_t symbol_diamond_palettes[2];
extern const uint8_t symbol_diamond_tiles[64];

extern const metasprite_t* const symbol_diamond_metasprites[1];

#endif