//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_symbol_club_H
#define METASPRITE_symbol_club_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define symbol_club_TILE_ORIGIN 0
#define symbol_club_TILE_H 8
#define symbol_club_WIDTH 16
#define symbol_club_HEIGHT 16
#define symbol_club_TILE_COUNT 4
#define symbol_club_PIVOT_X 0
#define symbol_club_PIVOT_Y 0
#define symbol_club_PIVOT_W 16
#define symbol_club_PIVOT_H 16

BANKREF_EXTERN(symbol_club)

extern const palette_color_t symbol_club_palettes[2];
extern const uint8_t symbol_club_tiles[64];

extern const metasprite_t* const symbol_club_metasprites[1];

#endif