//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_symbol_heart_H
#define METASPRITE_symbol_heart_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define symbol_heart_TILE_ORIGIN 0
#define symbol_heart_TILE_H 8
#define symbol_heart_WIDTH 16
#define symbol_heart_HEIGHT 16
#define symbol_heart_TILE_COUNT 4
#define symbol_heart_PIVOT_X 0
#define symbol_heart_PIVOT_Y 0
#define symbol_heart_PIVOT_W 16
#define symbol_heart_PIVOT_H 16

BANKREF_EXTERN(symbol_heart)

extern const palette_color_t symbol_heart_palettes[2];
extern const uint8_t symbol_heart_tiles[64];

extern const metasprite_t* const symbol_heart_metasprites[1];

#endif